src/Intracto/SecretSantaBundle/Controller/PoolController.php, src/Intracto/SecretSantaBundle/Entity/EntryService.php, src/Intracto/SecretSantaBundle/Entity/EntryShuffler.php, src/Intracto/SecretSantaBundle/Resources/translations/validators.en.yml, src/Intracto/SecretSantaBundle/Resources/translations/validators.nl.yml, src/Intracto/SecretSantaBundle/Tests/EntryShufflerTest.php
Based on @TomCan  code.
Improved it with a time limit of 10 sec.
Then an error wil be shown to the user to try again or remove some combinations.
The valdiator already shuffles the entries, checking for a valid match. 
The EntryShuffler service then re-uses that shuffled list and saves it.
=> Re-enable and improve excludes

Vagrantfile, shell_provisioner/module/php.sh
2 problems:
1) PHP-APC package is not included in provisioner, but required for ApcClassLoader. Fixed by adding php-apc to shellprovisioning script
2) On Windows, mounting of shared folder fails when the additional NFS options are passed to the fallback vboxfs shared folder provider. Added an OS Check to the Vagrantfile that will use the appropriate command for Windows hosts.
=> 2 problems with provisioning

src/Intracto/SecretSantaBundle/Command/MailqueueCommand.php, src/Intracto/SecretSantaBundle/Command/SendBatchMailsCommand.php, src/Intracto/SecretSantaBundle/Entity/EntryRepository.php, src/Intracto/SecretSantaBundle/Mailer/Mail/BatchEmptyWishlistReminder.php, src/Intracto/SecretSantaBundle/Mailer/Mail/BatchEntryMail.php, src/Intracto/SecretSantaBundle/Mailer/Mail/BatchViewEntryReminder.php, src/Intracto/SecretSantaBundle/Mailer/Mailer.php
- limit the number of entries handled at a time, drasticly reduces the
time and memory the entitymanager needs to process the updates.
- command had a --time-limit option that will make the command stop after
a number of seconds.
eg. The following command could be used in combination with a crontab set
to run each minute
php app/console intracto:mails:reminders:send --time-limit=50 --force
Entries are processed in batches (default 10, configurable) and a single flush of the spool is done at the end of the batch. Keeping batches small is advised (run more often with smaller batches).
A permanent fix/rewrite of the batch e-mail system is also in the make (enhancement for 2016?).
=> Temporary fix for #41 - memory issue with reminder e-mails

src/Intracto/SecretSantaBundle/Controller/ReportController.php, src/Intracto/SecretSantaBundle/Query/EntryReportQuery.php, src/Intracto/SecretSantaBundle/Query/GoogleAnalyticsQuery.php, src/Intracto/SecretSantaBundle/Query/IpReportQuery.php, src/Intracto/SecretSantaBundle/Query/PoolReportQuery.php, src/Intracto/SecretSantaBundle/Query/SeasonComparisonReportQuery.php, src/Intracto/SecretSantaBundle/Query/WishlistReportQuery.php, src/Intracto/SecretSantaBundle/Resources/config/services.xml, src/Intracto/SecretSantaBundle/Resources/public/css/report.css, src/Intracto/SecretSantaBundle/Resources/views/Report/report.html.twig
Subissue of #61 
Each season shows how much the number has increased or decreased compared to the previous season.
Google Analytics charts now have their legend on the right side and are enlarged for easier reading. The language codes that belong to the same main language have been put together in a category so that we get a better overview. This might still need some refining. Now there are many categories and maybe of same of them can be merged together, not sure about that. The array with all the language categories might need to be sorted by amount of people, but the sorting did not work out.
=> Added comparison with previous season | Larger charts

src/Intracto/SecretSantaBundle/Controller/ReportController.php, src/Intracto/SecretSantaBundle/Resources/views/Report/report.html.twig
Subissue of #61
Added one day caching to reports. Every season has the possibility to be cached, also 'all time'-data will be cached, prevents long loading times and excess API calls.
=> Report caching

src/Intracto/SecretSantaBundle/Controller/PoolController.php, src/Intracto/SecretSantaBundle/Mailer/MailerService.php, src/Intracto/SecretSantaBundle/Query/EntryReportQuery.php, src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml, src/Intracto/SecretSantaBundle/Resources/views/Emails/poolupdate.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Emails/poolupdate.txt.twig, src/Intracto/SecretSantaBundle/Resources/views/Pool/manage.html.twig
Follows up on #94 
Subissue of #93
Admin can send an update on the party status to all participants by clicking a link on his manage-page. Participants get an overview on where and when the party will take place and gets to see how many people the admin invited, how many people already confirmed their participation and how many people already added items to their wishlist. This should encourage participants to take action if needed.
=> Pool update for participants

src/Intracto/SecretSantaBundle/Controller/PoolController.php, src/Intracto/SecretSantaBundle/Entity/Pool.php, src/Intracto/SecretSantaBundle/Mailer/MailerService.php, src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml, src/Intracto/SecretSantaBundle/Resources/views/Emails/admin_wishlists.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Emails/admin_wishlists.txt.twig, src/Intracto/SecretSantaBundle/Resources/views/Entry/index.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Pool/manage.html.twig
Subissue of #37 & #93 
Similar to requesting the Secret Santa pairs, the admin can request an email with the wishlist of every single member in his pool.
=> Expose wishlists to admin

src/Intracto/SecretSantaBundle/Resources/public/css/mediaqueries.css, src/Intracto/SecretSantaBundle/Resources/public/css/update.css, src/Intracto/SecretSantaBundle/Resources/views/Entry/index.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Helpers/prototypeWishlist.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Pool/create.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Pool/exclude.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Pool/forgotLink.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Pool/manage.html.twig, src/Intracto/SecretSantaBundle/Resources/views/base.html.twig
Subissue of #67 
Project contained classes that were used in older version of Font Awesome and/or Bootstrap which caused empty spaces where the icons should have been. Those classes got updated.
Most tables used to cause horizontal scroll on mobile devices, this shouldn't happen anymore. Input fields and buttons (especially on the manage page) and the language selector are styled to look better on mobile devices.
=> Font awesome update + better look on mobile devices

src/Intracto/SecretSantaBundle/Controller/PoolController.php
Bug introduced in #124, always dispatch event so mails are send to people (currenty pools of 3 people don't receive mails)
=> Send event to dispatch pool mails (even if only 3 participants)

src/Intracto/SecretSantaBundle/Command/SendEmptyWishlistReminderCommand.php, src/Intracto/SecretSantaBundle/Command/SendEntryViewReminderCommand.php, src/Intracto/SecretSantaBundle/Query/EntryMailQuery.php
Currently when the cli command sends batch mails the send status is flushed at the end of the loop. When an exception occurs the status is not saved
=> Catch exceptions in mail command and flush the status for send mails

app/config/config.yml
https://insight.sensiolabs.com/projects/5e845a60-cf8f-4e83-97d3-ecacb19cd091/analyses/51?status=violations#413777285
this is because of doctrine 2.5 see http://blog.insight.sensiolabs.com/2014/12/22/making-symfony-bootable-with-dbal-2-5.html
this is the suggested fix. Please OK and merge
=> Insights needs a DB to find this version and can't

app/AppKernel.php, app/config/config.yml, composer.json, composer.lock, src/Intracto/SecretSantaBundle/DependencyInjection/Compiler/FormCompilerPass.php, src/Intracto/SecretSantaBundle/Features/Context/Bootstrap/PoolContext.php, src/Intracto/SecretSantaBundle/Form/Extension/DateTypeExtension.php, src/Intracto/SecretSantaBundle/Form/PoolType.php, src/Intracto/SecretSantaBundle/Form/UpdatePoolDetailsType.php, src/Intracto/SecretSantaBundle/IntractoSecretSantaBundle.php, src/Intracto/SecretSantaBundle/Resources/config/services.xml, src/Intracto/SecretSantaBundle/Resources/views/Form/jquery_layout.html.twig, src/Intracto/SecretSantaBundle/Resources/views/base.html.twig, src/Intracto/SecretSantaBundle/Twig/Extension/FormExtension.php
This PR removes the genemu form bundle (as we only used the modified date type) and replaces the datetype with a custom version using [uxsolutions/bootstrap-datepicker](https://github.com/uxsolutions/bootstrap-datepicker).
TODO:
Note to self: Tag a new version of bootstrap-datepicker (1.7.0) and use this version instead of 1.6.4.
=> [WIP] Replace genemu/form-bundle with custom datetype. Fixes #188

src/Intracto/SecretSantaBundle/Command/ExportMailsCommand.php, src/Intracto/SecretSantaBundle/Query/EntryReportQuery.php
CSV files are now generated by PHP instead of mysql and are saved to /tmp instead of /export. See #138
=> Fix #138: Fixing CSV export

src/Intracto/SecretSantaBundle/Form/Extension/DateTypeExtension.php, src/Intracto/SecretSantaBundle/Resources/views/Form/jquery_layout.html.twig
Touchboard is now disabled when using a mobile device and month is now corrected: month is now given in MM (full month) instead of mm (Numbers only).
Closes #196
=> Fix #196 : Fix of datepicker issues

src/Intracto/SecretSantaBundle/Command/ExportMailsCommand.php, src/Intracto/SecretSantaBundle/Query/EntryReportQuery.php, src/Intracto/SecretSantaBundle/Resources/config/services.xml
CSV export of the administrators now contains an url to reuse their previously used pools. Closes #202
=> Added reuse url to admin export

src/Intracto/SecretSantaBundle/Controller/Pool/ManagementController.php
After updating a pool, mails are sent directly instead of flagged for cron.
=> #157 Update mails are now sent directly

src/Intracto/SecretSantaBundle/Query/EntryReportQuery.php
Query file already has router injected, but tried to load router with getContainer. This throws a undefined method error. See #205
=> Bug fix: Exports did not work due to undefined method

src/Intracto/SecretSantaBundle/Controller/Pool/PoolController.php, src/Intracto/SecretSantaBundle/Form/Type/PoolExcludeEntryType.php
Fix of 2 deprecations: Cascade_validation has been removed, constraints => valid should be used. And PoolExcludeEntryType is now called correctly in PoolController. (#193)
=> Fix of Deprecations in PoolExcludeEntryType

src/Intracto/SecretSantaBundle/Twig/Extension/FormExtension.php, src/Intracto/SecretSantaBundle/Twig/LinkifyExtension.php
[sensiolabs-de/deprecation-detector](https://github.com/sensiolabs-de/deprecation-detector) (goeie tip @rvanginneken) had nog 4 deprecations gevonden die nog in onze code zaten. Hierbij gefixt en we lijken dus klaar te zijn voor symfony 3 (tool is nog in alpha dus zou eventueel wel deprecations kunnen gemist hebben)
```
Finished searching for deprecations.
Rendering output...
+---+-------------------------------------------------------------------------------------------------+------+----------------------------------------------------------------+
| # | Usage                                                                                           | Line | Comment                                                        |
+---+---------------------------------------------------------------- …
```
=> Fixed twig deprecations

src/Intracto/SecretSantaBundle/Controller/Participant/ParticipantController.php, src/Intracto/SecretSantaBundle/Controller/Party/ManagementController.php, src/Intracto/SecretSantaBundle/Controller/Party/PartyController.php, src/Intracto/SecretSantaBundle/Resources/translations/messages.de.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.no.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.pl.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.pt.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.ru.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hans.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hant.yml, src/Intracto/SecretSantaBundle/Resources/views/Party/exclude.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.js.twig, src/Intracto/SecretSantaBundle/Validator/ParticipantHasValidExcludesValidator.php, src/Intracto/SecretSantaBundle/Validator/PartyHasValidExcludesValidator.php
Party doesn’t start automatically anymore when admin confirms email. Instead party is in a frozen state, no emails are sent and all changes are possible. When the admin decides to start the party, the participants are shuffled and the mails are sent out. When started with excludes, limited changes are possible. When started without, most changes are possible, but not encouraged. Workaround for #151 . 
It's now also possible to edit the name of a participant. To ensure correct form handling and increase ux (showing error's and possibility to edit) handling of this form is now done with ajax. See #166 
Closes #151 & #166
=> Parties don't start automaticly anymore

composer.json, composer.lock, grumphp.yml, src/Intracto/BehatBundle/DependencyInjection/IntractoBehatExtension.php, src/Intracto/BehatBundle/Features/Context/Bootstrap/LanguageContext.php, src/Intracto/SecretSantaBundle/Query/SeasonComparisonReportQuery.php, src/Intracto/SecretSantaBundle/Tests/Twig/LinkifyExtensionTest.php
Grumphp has been updated to 0.11.4, and phpstan has been configured to run during Grumphp tests. Since no paths can be configured in phpstan configuration files, global runs of Grumphp (grumphp run) might fail. Git specific grumphp runs (git hook & grumphp git:pre-commit) should run without any problem. Closes #223
=> Added phpstan to Grumphp

src/Intracto/SecretSantaBundle/Controller/Party/ForgotManagementURLController.php, src/Intracto/SecretSantaBundle/Entity/ParticipantRepository.php, src/Intracto/SecretSantaBundle/Entity/PartyRepository.php, src/Intracto/SecretSantaBundle/Form/Type/ForgotLinkType.php, src/Intracto/SecretSantaBundle/Mailer/MailerService.php, src/Intracto/SecretSantaBundle/Resources/translations/messages.de.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.no.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.pl.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.pt.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.ru.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hans.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hant.yml, src/Intracto/SecretSantaBundle/Resources/views/Emails/forgotLink.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Emails/forgotLink.txt.twig, src/Intracto/SecretSantaBundle/Resources/views/Party/forgotLink.html.twig
The forgot email functionality now also works for participants, and not only for admins. When a user requests an email, he/she will receive an overview of all the parties he/she participates in and the parties he/she created. Only the parties of the past week and future are given. As described in #250
=> #250: Improved forgot email functionality 

src/Intracto/SecretSantaBundle/Resources/translations/messages.de.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.no.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.pl.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.pt.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.ru.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hans.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hant.yml, src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.html.twig
Some messages on the manage page are now hidden when the party isn't started yet:
- The info box containing the tip to check if someone opened their mail
- The warning when deleting a participant is less severe
Closes #259
=> Hiding some messages if party isn't started yet

src/Intracto/SecretSantaBundle/Controller/Party/ManagementController.php, src/Intracto/SecretSantaBundle/Controller/Party/PartyController.php, src/Intracto/SecretSantaBundle/Entity/Party.php, src/Intracto/SecretSantaBundle/Form/Type/UpdatePartyDetailsType.php, src/Intracto/SecretSantaBundle/Mailer/MailerService.php, src/Intracto/SecretSantaBundle/Resources/translations/messages.de.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.no.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.pl.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.pt.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.ru.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hans.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hant.yml, src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.html.twig
The personal message which is sent with the initial email, to the participants can now be changed after the creation of the party. This can't be changed when party has started. Since only the custom message is saved in the database now, and not the whole email, only parties created after 19th of April 2017 can use this function.
Closes #260
=> #260 : Personal message can now be updated after creation

src/Intracto/SecretSantaBundle/Form/Type/WishlistType.php
CSRF Was removed  in #270 due to problems with saving the wishlist if the site was open for a longer time (on tablet etc..), but CSRF check was not disabled. Thence wishlists were not saved anymore.
Closes #281
=> Fix #281 : Adding items to wishlist fixed

src/Intracto/SecretSantaBundle/Resources/translations/messages.de.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.no.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.pl.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.pt.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.ru.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hans.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hant.yml, src/Intracto/SecretSantaBundle/Resources/views/Participant/exposeAll.html.twig, src/Intracto/SecretSantaBundle/Resources/views/Wishlist/showAll.html.twig
Placed a link back to the manage on the pages where you can view all matches and view all the wishlists from the participants.
Closes #280
=> #280 Link back to manage page from wishlist/matches pages

behat.yml.dist, src/Intracto/Behat/Features/Context/Bootstrap/UnsubscribeContext.php, src/Intracto/Behat/Features/unsubscribe.feature, src/Intracto/SecretSantaBundle/Controller/UnsubscribeController.php, src/Intracto/SecretSantaBundle/Form/Handler/UnsubscribeFormHandler.php, src/Intracto/SecretSantaBundle/Resources/config/services.xml, src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml, src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml, src/Intracto/SecretSantaBundle/Resources/views/Participant/unsubscribe.html.twig
Moved the app logic away from the controller
- Make use of the doctrine paramconverter
- Use a form handler class to remove all application logic for handling forms
With this refactor I've also fixed a bug when an user did not select any of the two checkboxes on the page (+ behat tests for this page and the fixed bug)
=> Refactor unsubscribe controller

src/Intracto/SecretSantaBundle/Controller/ForgotURLController.php, src/Intracto/SecretSantaBundle/Controller/HomepageController.php, src/Intracto/SecretSantaBundle/Controller/Participant/DumpParticipantsController.php, src/Intracto/SecretSantaBundle/Controller/Participant/ExposeParticipantsController.php, src/Intracto/SecretSantaBundle/Controller/Participant/ParticipantController.php, src/Intracto/SecretSantaBundle/Controller/Participant/ResendParticipantController.php, src/Intracto/SecretSantaBundle/Controller/Participant/ShowController.php, src/Intracto/SecretSantaBundle/Controller/ParticipantCommunicationController.php, src/Intracto/SecretSantaBundle/Controller/Party/ManagementController.php, src/Intracto/SecretSantaBundle/Controller/Party/PartyController.php, src/Intracto/SecretSantaBundle/Controller/Party/SendPartyUpdateController.php, src/Intracto/SecretSantaBundle/Controller/ReuseController.php, src/Intracto/SecretSantaBundle/Controller/TrackingController.php, src/Intracto/SecretSantaBundle/Controller/UnsubscribeController.php
This PR does some general controller clean up. This prepares the controllers so we extended from `AbstractController` to avoid calling the container directly
- Use strict_types
- Make sure we use the controller helper functions instead of accessing the container directly
- Some general code style
=> General controller cleanup

src/Intracto/SecretSantaBundle/Twig/Extension/FormExtension.php
`TwigRendererInterface` is deprecated and in 3.4 the `twig.renderer` service will switch to the `FormRenderer` class
=> Forward compatibility with sf 3.4 autowiring

src/Intracto/SecretSantaBundle/Controller/Party/PartyController.php
Fixes issue with language switcher on the homepage. Reproducible like this:
create empty party -> form errors -> you are now at /party/create (POST only)
switch language -> 404 because page is POST only
=> Fix: Language switcher

src/Intracto/SecretSantaBundle/Form/Extension/DateTypeExtension.php, src/Intracto/SecretSantaBundle/Resources/views/Form/jquery_layout.html.twig
Different approach and more "stable" fix for date issue from #352. Closes #352.
@tvlooy the fix from #352 broke the conversion of text input to `DateTime` object. Original issue for the fix in #200. This should be fixed now for all cases, eg the correct print in frontend and correct conversion to php object.
=> Split dateformat for frontend/php to fix bug

app/Resources/translations/messages.ru.yml
'Количество' in english 'count'. 'How much money to spend on a gift' in russian is more close to 'amount to spend'
=> Change participant RU headers

.travis/before_install.sh, .travis/script.sh, app/config/config_test_travis.yml, composer.lock
Some extra checks during the build to avoid small mistakes to be deployed to production. The extra checks are:
- Lint the yaml config files
- Lint the twig files
- Check for security vulnerabilities
- Validate the composer file
- Validate the doctrine mapping files
I've also updated symfony to fix an error from the security checker (see the full commit message of 
0ac0fd4 for more info) and remove a duplicate key in the travis_test config
=> Added extra travis checks

.travis/script.sh, composer.json, composer.lock
Travis has upgraded their build container, so we will soon get them in our builds. This PR adds support for those new containers (newer chrome version, now 60 next will be 62), this way we support the current container and the updated one. Also locked selenium-standalone on the 3.4 version because I had issues with the newer ones.
See: https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
=> Fixes for the upgraded travis containers

app/Resources/translations/messages.nl.yml
Wenslijst en verlanglijst wordt beide gebruikt in de vertalingen. 
Ik stel voor 1 te kiezen en dit consistent te gebruiken in de vertalingen.
=> Fix typo's

app/Resources/translations/messages.en.yml, app/Resources/translations/messages.fr.yml, app/Resources/translations/messages.nl.yml, app/Resources/translations/messages.no.yml, app/Resources/translations/messages.pt.yml
The way we can easily link to specific parts of the faq. Ex. https://secretsantaorganizer.com/faq#manage
=> Make sure the faq title links have correct anchors

src/Intracto/SecretSantaBundle/Controller/Party/ManagementController.php, src/Intracto/SecretSantaBundle/Controller/WishlistController.php
Sometimes there is an error when party admins send a party update, or when a participant updates his/her wishlist.
The problem is that it validates the complete object tee, including data that is not changed. Eg: update party -> all participants are validated. Eg: update a wishlist -> participant, party and participants are validated.
Because we have a validator on the participant to check if he/she is blacklisted, it is possible that suddenly a participant will not validate anymore.
I think that validator is not in the right place there, let that be clear.
But as a good workaround I think just limiting the form validation to the data that actually changed is a good fix here.
=> only validate relevant data

src/Intracto/Behat/DataFixtures/LoadPartyData.php, src/Intracto/Behat/Features/Context/FeatureContext.php, src/Intracto/SecretSantaBundle/Command/FixMissingPartyWishlistsurlCommand.php, src/Intracto/SecretSantaBundle/Controller/WishlistController.php, src/Intracto/SecretSantaBundle/Entity/Party.php, src/Intracto/SecretSantaBundle/Resources/config/doctrine/Participant.orm.xml, src/Intracto/SecretSantaBundle/Resources/config/doctrine/Party.orm.xml, src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.html.twig
Todo after deploy:
- run intracto:fix:missing_party_wishlists
- open new PR to:
- remove FixMissingPartyWishlistsurlCommand
- add unique to Party.orm.xml (see todo)
=> #362: use separate hash for exposing wishlists

app/config/legacy_aliases.yml, app/config/services.yml, src/Intracto/SecretSantaBundle/Command/EnrichParticipantInfoCommand.php, src/Intracto/SecretSantaBundle/Controller/Participant/DumpParticipantsController.php, src/Intracto/SecretSantaBundle/Repository/ParticipantRepository.php, src/Intracto/SecretSantaBundle/Repository/PartyRepository.php, src/Intracto/SecretSantaBundle/Resources/config/doctrine/Participant.orm.xml, src/Intracto/SecretSantaBundle/Resources/config/doctrine/Party.orm.xml
- Use local service binding to remove some extra service config with duplicate parameters.
- Use the "ServiceEntityRepository" class to extend repositories from (introduced in doctrineBundle 1.8.0+) to avoid explicitly defining repositories in the service config
=> Use new autowire features to simplify the service config

.styleci.yml
These are files we don't "own" and cache files. So don't fix those. For example on each `composer update` the `SymfonyRequirements` file will change codestyle to the default.
=> Don't fix files in var dir

Makefile, deploy.sh
Make the output of a ```make deploy``` pretty. If you want all the output for debugging, use ```make deploy-debug``` that has the output how it was. While this is a bit of overhead, I think it's acceptable.
=> Pretty output

docker/Dockerfile-php
Intl extension was missing from the docker container, yielding an error on a number of pages.
=> Added intl extension

package.json
Everything in the `node_modules/.bin/` folder can be executed directly.
=> Simplify scripts

assets/css/update.css
Add fallback fonts. These are all needed to support foreign characters or emojis. The fallback fonts are copied from Bootstrap.
Fixes https://github.com/Intracto/SecretSanta/issues/480
=> Add fallback fonts

package.json, webpack.config.js, yarn.lock
Following packages are updated:
@symfony/webpack-encore 
node-sass 
sass-loader
jquery-csv@1.0.21
=> Frontend packages upgraded to latest

src/Controller/Party/PartyController.php
$appEnv parameter not passed everywhere. Removed this and directly get env name from kernel instead.
=> Get environment from kernel closes #553

package.json, yarn.lock
The request package through 2.88.2 for Node.js and the @cypress/request package prior to 3.0.0 allow a bypass of SSRF mitigations via an attacker-controller server that does a cross-protocol redirect (HTTP to HTTPS, or HTTPS to HTTP).
=> Upgrade Cypress

src/Service/UrlTransformerService.php, src/Twig/LinkifyExtension.php, tests/php/unit/Service/UrlTransformerTest.php, tests/php/unit/Twig/LinkifyExtensionTest.php
Add UrlTransformer service and integrate with Linkify extention.
UrlTransformer allows us to change user-generated links if the hostname matches a specific pattern. This can be used to add affiliate tags or even completely rewrite the url.
=> Add UrlTransformerService and integrate in LinkifyExtension
