composer.json
composer.lock
src/Intracto/SecretSantaBundle/Entity/Entry.php

Fix #2 : Added strict email validation + updated composer

---

src/Intracto/SecretSantaBundle/Controller/PoolController.php
src/Intracto/SecretSantaBundle/Entity/Entry.php
src/Intracto/SecretSantaBundle/Entity/Pool.php
src/Intracto/SecretSantaBundle/Entity/PoolRepository.php
src/Intracto/SecretSantaBundle/Entity/PoolService.php
src/Intracto/SecretSantaBundle/Form/ForgotLinkType.php
src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml
src/Intracto/SecretSantaBundle/Resources/views/Emails/forgotlink.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/forgotlink.txt.twig
src/Intracto/SecretSantaBundle/Resources/views/Pool/create.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Pool/forgotLink.html.twig

**Still work in progress**
This pr fixes issue #1 
Done:
```
UPDATE Entry SET poolAdmin = true WHERE id IN (SELECT sub.admin_entry_id FROM (SELECT
(SELECT id FROM Entry WHERE poolId = p.id ORDER BY id ASC LIMIT 1) as admin_entry_id FROM Pool p) sub);
```
Todo:

forgot manage link

---

deploy.sh

Did not test this, please do before running in prod ;).

Deploy.sh: optimize composer install and run cmds in prod env

---

src/Intracto/SecretSantaBundle/Mailer/Mailer.php

Fix for failing cron (current error was incorrect email address)

Added error handling in reminder mailer

---

src/Intracto/SecretSantaBundle/Entity/EntryRepository.php
src/Intracto/SecretSantaBundle/Entity/Pool.php

Fix for longer locale strings like "zh-Hans" & "zh-Hant"
plus small phpdoc fix

Fix locale db column length

---

src/Intracto/SecretSantaBundle/Resources/public/js/secretsanta.js

Added logic so the left header links back to the homepage, this way the language switcher still works.
Fixes #33

Added header link to left header div

---

src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.pt.yml

#52: Fix: changed a weird sentence that was causing confusion

---

src/Intracto/SecretSantaBundle/Entity/PoolRepository.php
src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml

- Now send manage links for parties with dates from 1 week ago until the future
Closes #56

Fixes to the resend manage link query/page

---

src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml
src/Intracto/SecretSantaBundle/Resources/views/Pool/manage.html.twig

#50: Feature: added extra view to see if someone filled in their wishlist on admin view

---

src/Intracto/SecretSantaBundle/Controller/EntryController.php
src/Intracto/SecretSantaBundle/Entity/Entry.php
src/Intracto/SecretSantaBundle/Resources/views/Entry/index.html.twig

Logging the IP-address of users as soon as they check their Secret Santa.
Fixed error on Entry index view, still used old notation for eventdate.

Log IP-address for future reports

---

src/Intracto/SecretSantaBundle/Form/PoolType.php
src/Intracto/SecretSantaBundle/Resources/views/Pool/create.html.twig

issue #67 Selecting date from the past to create an event and picking native datepicker.

bug fix selecting dates from the past

---

src/Intracto/SecretSantaBundle/Resources/public/js/pool.create.js
src/Intracto/SecretSantaBundle/Resources/views/Pool/create.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Report/report.html.twig

sub issue of #67
fix validation

validation

---

src/Intracto/SecretSantaBundle/Entity/Entry.php
src/Intracto/SecretSantaBundle/Query/EntryReportQuery.php
src/Intracto/SecretSantaBundle/Query/FeaturedYearsQuery.php
src/Intracto/SecretSantaBundle/Query/IpReportQuery.php
src/Intracto/SecretSantaBundle/Query/PoolReportQuery.php
src/Intracto/SecretSantaBundle/Query/ReportQuery.php
src/Intracto/SecretSantaBundle/Query/WishlistReportQuery.php

… | Made get/setIpv4 and get/setIpv6 private functions
sub issue of #61

Typehinting in query classes | Public to private functions in Entry entity

---

src/Intracto/SecretSantaBundle/Resources/public/css/report.css
src/Intracto/SecretSantaBundle/Resources/views/Report/report.html.twig

sub issue of #61 
Added background to each div to make clear the difference.
Changed colors of Google Charts.
Restructured some of the report Twig and CSS-file.
Code to see comparison between seasons will be added in other pull request, this only adds visual elements, no logic.

Styling fixes to report page

---

src/Intracto/SecretSantaBundle/Controller/ReportController.php

Infinite caching for previous seasons

---

src/Intracto/SecretSantaBundle/Resources/public/css/mediaqueries.css
src/Intracto/SecretSantaBundle/Resources/public/css/update.css
src/Intracto/SecretSantaBundle/Resources/public/js/secretsanta.js
src/Intracto/SecretSantaBundle/Resources/views/Pool/create.html.twig
src/Intracto/SecretSantaBundle/Resources/views/base.html.twig

Fixed #86 
The language selector on mobile is not working and has been styled.

Language selector on mobile

---

src/Intracto/SecretSantaBundle/Controller/EntryController.php
src/Intracto/SecretSantaBundle/Controller/PoolController.php
src/Intracto/SecretSantaBundle/Form/AddEntryType.php
src/Intracto/SecretSantaBundle/Query/EntryReportQuery.php
src/Intracto/SecretSantaBundle/Resources/public/css/update.css
src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml
src/Intracto/SecretSantaBundle/Resources/views/Pool/create.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Pool/manage.html.twig
src/Intracto/SecretSantaBundle/Resources/views/base.html.twig

Subissue of #31 and #60 
Admin can add people to his/her pool even after the pool is created. Removing people from a pool is possible as long as the deleted user is not the pooladmin. If the admin used excludes on creating the pool, deleting users is prevented to avoid excluded entries from being coupled anyway.

Adding and removing people from pool

---

composer.json
composer.lock
grumphp.yml

Fix for #101 
Upon committing, GrumPHP will check for coding standards in your project. Each commit now needs to refer to a Git Issue, this issue has to be mentioned in your commit by using a # and the issue number before your commit message.

Implemented GrumPHP

---

src/Intracto/SecretSantaBundle/Controller/EntryController.php
src/Intracto/SecretSantaBundle/Entity/Pool.php

Subissue of #58 & #89
Replaced new Response with new JsonResponse
Fixed empty field on pool reuse view, location is now filled in when the page gets loaded.

Minor fixes to save wishlist & pool reuse

---

src/Intracto/SecretSantaBundle/Controller/PoolController.php
src/Intracto/SecretSantaBundle/Form/UpdatePoolDetailsType.php
src/Intracto/SecretSantaBundle/Mailer/MailerService.php
src/Intracto/SecretSantaBundle/Resources/public/css/update.css
src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml
src/Intracto/SecretSantaBundle/Resources/views/Emails/updatedparty.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/updatedparty.txt.twig
src/Intracto/SecretSantaBundle/Resources/views/Pool/manage.html.twig

Subissue of #38 
Admins get the option to edit the details of the party they created. All participants will be notified as soon as the admin hits the submit button.

Admins can update the details of their party

---

app/AppKernel.php
app/config/config.yml
app/config/config_dev.yml
app/config/routing_dev.yml
composer.json
composer.lock
src/Intracto/SecretSantaBundle/Controller/EntryController.php
src/Intracto/SecretSantaBundle/Controller/PoolController.php
src/Intracto/SecretSantaBundle/Entity/EntryService.php
src/Intracto/SecretSantaBundle/Form/ExcludeEntryType.php
src/Intracto/SecretSantaBundle/Form/PoolExcludeEntryType.php
src/Intracto/SecretSantaBundle/Resources/config/services.xml

- Removed some extra dependencies (not necessary and can be replaced by symfony methods)
- Some general code cleanup

Code cleanup

---

src/Intracto/SecretSantaBundle/Controller/PoolController.php

Annotation dependency injection was removed in #125 but the bugfix in #127 still had some old code

Hotfix for bug in merged branches

---

.travis.yml
.travis/after_failure.sh
.travis/before_install.sh
.travis/before_script.sh
.travis/install.sh
.travis/script.sh
composer.json

Added the basic config for travis-ci builds. Currently only the existing phpunit tests are run on each new PR and push/merge to master.
I will open a separate pr with the addition of a behat test environment and some behat tests

Basic travis-ci setup

---

.gitignore
.travis.yml
.travis/after_failure.sh
.travis/before_install.sh
.travis/before_script.sh
.travis/files/behat-travis.yml
.travis/install.sh
.travis/script.sh
app/config/config_test_travis.yml
app/config/router_test_travis.php
behat.yml.dist
composer.json
composer.lock
src/Intracto/SecretSantaBundle/Behat/Page/Homepage.php
src/Intracto/SecretSantaBundle/Behat/Page/ParticipantExclude.php
src/Intracto/SecretSantaBundle/Behat/Page/PoolCreated.php
src/Intracto/SecretSantaBundle/Features/Context/Bootstrap/PoolContext.php
src/Intracto/SecretSantaBundle/Features/Context/FeatureContext.php
src/Intracto/SecretSantaBundle/Features/create_pool.feature
web/app_test_travis.php

Updated the travis build config to run behat tests on each commit/pr

Integrated behat tests in the travis build suite

---

src/Intracto/SecretSantaBundle/Query/EntryReportQuery.php
src/Intracto/SecretSantaBundle/Query/PoolReportQuery.php
src/Intracto/SecretSantaBundle/Resources/views/Report/report.html.twig

Some fixes to the report data covering all seasons. Current data was a cumulative view but now it shows real numbers for each season

Report data fixes

---

src/Intracto/SecretSantaBundle/Entity/Entry.php
src/Intracto/SecretSantaBundle/Entity/Pool.php

These indexes are mainly used in cronjobs. Your MySQL server will approve ;)

Added indexes to Pool and Entry entities

---

src/Intracto/SecretSantaBundle/Entity/Entry.php
src/Intracto/SecretSantaBundle/Entity/EntryRepository.php
src/Intracto/SecretSantaBundle/Entity/EntryService.php
src/Intracto/SecretSantaBundle/Entity/EntryShuffler.php
src/Intracto/SecretSantaBundle/Entity/Pool.php
src/Intracto/SecretSantaBundle/Entity/WishlistItem.php

Remove some unused fields getters/setters and some style cleanups

---

.travis.yml

Test PR's against the current used version (5.6) and the latest php version (7.1)

Bumped php version to 7.1

---

app/config/parameters.yml.dist
src/Intracto/SecretSantaBundle/Resources/translations/messages.no.yml

@tvlooy the changes to the production parameters files will need to be done manually irc?

Norwegian translations

---

app/SymfonyRequirements.php
app/check.php
composer.lock
web/config.php

This needs testing.
Summary:
```
"name": "doctrine/annotations",
-            "version": "v1.2.7",
+            "version": "v1.3.1",
--
"name": "doctrine/cache",
-            "version": "v1.6.0",
+            "version": "v1.6.1",
--
"name": "doctrine/common",
-            "version": "v2.6.1",
+            "version": "v2.7.2",
--
"name": "doctrine/dbal",
-            "version": "v2.5.4",
+            "version": "v2.5.9",
--
"name": "doctrine/doctrine-bundle",
-            "version": "1.6.2",
+            "version": "1.6.6",
--
"name": "doctrine/orm",
-            "version": "v2.5.4",
+            "version": "v2.5.6",
--
"name": "egulias/email-validator",
-            "version": "1.2.12",
+            "version": "1.2.13",
--
"name": "google/apiclient",
-            "version": "1.1.7",
+ …
```

Symfony updates

---

web/app.php
web/app_dev.php

Recommended by Symfony for PHP 7.x
See https://github.com/symfony/symfony-standard/pull/1030/files
@acrobat ok?

Remove cache loader

---

src/Intracto/SecretSantaBundle/Resources/views/Emails/baseEmail.html.twig

Improve spam score by adding alt tag to images in emails. See #218

Added alt tag to images in emails

---

src/Intracto/SecretSantaBundle/Controller/ParticipantCommunicationController.php
src/Intracto/SecretSantaBundle/Mailer/MailerService.php
src/Intracto/SecretSantaBundle/Resources/translations/messages.de.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.no.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.pl.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.pt.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.ru.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hans.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hant.yml
src/Intracto/SecretSantaBundle/Resources/views/Emails/anonymousMessage.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/anonymousMessage.txt.twig

Translation keys are corrected to correspond to the files where they are used. Keys updated for: ParticipantCommunicationController & Emails/AnonymousMessage.

Corrected translation keys

---

behat.yml.dist
src/Intracto/SecretSantaBundle/Features/Context/Bootstrap/LanguageContext.php
src/Intracto/SecretSantaBundle/Features/Context/Bootstrap/PoolContext.php
src/Intracto/SecretSantaBundle/Features/is_translatable.feature

Our main focus was here to be able to use multiple contexts without
errors.

Test translatable

---

composer.json
composer.lock
src/Intracto/SecretSantaBundle/Tests/ParticipantShufflerTest.php
src/Intracto/SecretSantaBundle/Tests/Twig/LinkifyExtensionTest.php

Travis uses phpunit6. Fixed the tests so we can use phpunit5 and 6 (phpunit5 has forward compatibility layer for namespaces)

Fixed phpunit6 incompatibilities

---

src/Intracto/SecretSantaBundle/Tests/Twig/LinkifyExtensionTest.php
src/Intracto/SecretSantaBundle/Twig/LinkifyExtension.php

Linkify now also detects www. links and makes them clickable. Closes #168

Links starting with www. without "://" are now also detected by linkify

---

app/console
app/phpunit.xml.dist
composer.json
web/app_test_travis.php

Removal of buildBootstrap task

---

src/Intracto/SecretSantaBundle/Controller/Party/ForgotManagementURLController.php
src/Intracto/SecretSantaBundle/Controller/ReuseController.php
src/Intracto/SecretSantaBundle/Entity/PartyRepository.php
src/Intracto/SecretSantaBundle/Form/Type/RequestReuseUrlType.php
src/Intracto/SecretSantaBundle/Mailer/MailerService.php
src/Intracto/SecretSantaBundle/Resources/translations/messages.de.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.no.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.pl.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.pt.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.ru.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hans.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hant.yml
src/Intracto/SecretSantaBundle/Resources/views/Emails/reuseLink.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/reuseLink.txt.twig
src/Intracto/SecretSantaBundle/Resources/views/Party/forgotLink.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Party/getReuseUrl.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Static/faq.html.twig

Added a page to request an email containing parties of the past 2 years, to reuse them. Also edited forgot management url. Both as described in #139. 
Closes #139

#139: Added a page to request a reuse url 

---

.travis/files/behat-travis.yml
app/AppKernel.php
app/config/config_test.yml
behat.yml.dist
composer.json
composer.lock
src/Intracto/BehatBundle/Features/Context/Bootstrap/PartyContext.php
src/Intracto/BehatBundle/Features/Context/Bootstrap/PartyManagementContext.php
src/Intracto/BehatBundle/Features/Context/EmailContext.php
src/Intracto/BehatBundle/Features/Context/FeatureContext.php
src/Intracto/BehatBundle/Features/create_party.feature
src/Intracto/BehatBundle/Features/party_management.feature
src/Intracto/BehatBundle/Page/Homepage.php
src/Intracto/SecretSantaBundle/Entity/ParticipantShuffler.php
src/Intracto/SecretSantaBundle/Entity/Party.php
web/app_test.php

This is a basic implementation of fixtures. This can definitely be improved but it is enough for now so we can start writing tests for the management page. I've included some basic tests as a start.
I'm going to test config a bit more (so still WIP for now) but it should be nearly done.

Basic implementation of fixtures + various fixes

---

app/AppKernel.php
app/config/config.yml
app/config/parameters.yml.dist
composer.json
composer.lock

Added bugsnag, to get extra information about current bugs.
Let's catch #234 !

Added bugsnag to the project

---

src/Intracto/SecretSantaBundle/Controller/ForgotURLController.php
src/Intracto/SecretSantaBundle/Resources/translations/messages.de.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.es.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.fr.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.nl.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.no.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.pl.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.pt.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.ru.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hans.yml
src/Intracto/SecretSantaBundle/Resources/translations/messages.zh-Hant.yml
src/Intracto/SecretSantaBundle/Resources/views/Static/faq.html.twig

Rename forgot_management_url to forgot_url

---

app/AppKernel.php
app/config/config.yml
app/config/parameters.yml.dist
composer.json
composer.lock

Bugsnag is no longer used, and can be removed. Closes #271

#271 Removal of Bugsnag

---

docs/behat.md

Some basic docs on behat (can be extended but should be sufficient for now). Closes #186

Basic behat docs

---

src/Intracto/SecretSantaBundle/Mailer/MailerService.php
src/Intracto/SecretSantaBundle/Query/FeaturedYearsQuery.php
src/Intracto/SecretSantaBundle/Query/ParticipantReportQuery.php
src/Intracto/SecretSantaBundle/Query/PartyReportQuery.php
src/Intracto/SecretSantaBundle/Resources/config/services.xml
src/Intracto/SecretSantaBundle/Service/UnsubscribeService.php

Fixes for some codestyle errors reported by phpstorm. Each commit is a different codestyle error

Codestyle fixes

---

behat.yml.dist
src/Intracto/Behat/Features/Context/Bootstrap/CommonPartyManagementContext.php
src/Intracto/Behat/Features/Context/Bootstrap/ParticipantContext.php
src/Intracto/Behat/Features/Context/Bootstrap/ResendPartyInfoContext.php
src/Intracto/Behat/Features/Context/Bootstrap/ReusePartyLinkContext.php
src/Intracto/Behat/Features/Context/Bootstrap/StartedPartyManagementContext.php
src/Intracto/Behat/Features/Context/Bootstrap/UnstartedPartyManagementContext.php
src/Intracto/Behat/Features/resend_party_info.feature
src/Intracto/Behat/Features/reuse_party_link.feature
src/Intracto/Behat/Services/JQueryHelper.php
src/Intracto/SecretSantaBundle/Resources/translations/messages.en.yml

Added the missing behat tests for reuse and forgot party url email
\+ some various fixes to the behat suite

Extra behat tests for missing endpoints

---

src/Intracto/Behat/Features/Context/Bootstrap/PartyContext.php
src/Intracto/Behat/Features/Context/EmailContext.php
src/Intracto/Behat/Page/Homepage.php
src/Intracto/Behat/Page/ParticipantExclude.php
src/Intracto/Behat/Page/PartyCreated.php
src/Intracto/SecretSantaBundle/Form/Extension/DateTypeExtension.php
src/Intracto/SecretSantaBundle/Resources/views/Emails/wishlistChanged.txt.twig

Some code style fixes reported by phpstorm/phpstan, each commit is a different rule. Some of them fix bugs.

Code style fixes

---

src/Intracto/SecretSantaBundle/Resources/views/Emails/anonymousMessage.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/baseEmailUnsubscribe.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/emptyWishlistReminder.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/forgotLink.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/participant.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/partyStatus.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/partyUpdate.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/pendingConfirmation.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/removedSecretSanta.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/reuseLink.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/reuseLink.txt.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/updatedParty.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/viewParticipantReminder.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/wishlistChanged.html.twig

Added utm tags to all urls in our emails + fix in a text only template
/cc SANTA-72

Utm tagging

---

src/Intracto/SecretSantaBundle/Controller/Party/PartyController.php
src/Intracto/SecretSantaBundle/Form/Handler/PartyFormHandler.php
src/Intracto/SecretSantaBundle/Mailer/MailerService.php
src/Intracto/SecretSantaBundle/Query/ParticipantReportQuery.php
src/Intracto/SecretSantaBundle/Resources/config/services.xml
src/Intracto/SecretSantaBundle/Resources/views/Party/manage/expired.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.html.twig

Moved application logic out of the controller:
- Make use of the doctrine paramconverter
- Use a form handler class to remove all application logic for handling forms

Refactor party controller

---

src/Intracto/Behat/Features/Context/Bootstrap/StartedPartyManagementContext.php
src/Intracto/Behat/Features/Context/Bootstrap/UnstartedPartyManagementContext.php
src/Intracto/SecretSantaBundle/Controller/Participant/ExposeParticipantsController.php
src/Intracto/SecretSantaBundle/Controller/Participant/ParticipantController.php
src/Intracto/SecretSantaBundle/Controller/Participant/ResendParticipantController.php
src/Intracto/SecretSantaBundle/Controller/Participant/ShowController.php
src/Intracto/SecretSantaBundle/Controller/Party/ManagementController.php
src/Intracto/SecretSantaBundle/Controller/Party/PartyController.php
src/Intracto/SecretSantaBundle/Controller/Party/SendPartyUpdateController.php
src/Intracto/SecretSantaBundle/Controller/WishlistController.php
src/Intracto/SecretSantaBundle/Mailer/MailerService.php
src/Intracto/SecretSantaBundle/Resources/views/Emails/partyStatus.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/partyStatus.txt.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/pendingConfirmation.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/pendingConfirmation.txt.twig
src/Intracto/SecretSantaBundle/Resources/views/Participant/exposeAll.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Party/created.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.js.twig
src/Intracto/SecretSantaBundle/Resources/views/Wishlist/showAll.html.twig

Use the doctrine paramconverter instead of manually fetching from db. This simplifies the code and moves more logic out of the controllers

Use the doctrine paramconverter

---

src/Intracto/SecretSantaBundle/Controller/Party/ManagementController.php
src/Intracto/SecretSantaBundle/Entity/ParticipantRepository.php
src/Intracto/SecretSantaBundle/Form/Handler/AddParticipantFormHandler.php
src/Intracto/SecretSantaBundle/Query/ParticipantReportQuery.php
src/Intracto/SecretSantaBundle/Resources/config/services.xml
src/Intracto/SecretSantaBundle/Service/PartyService.php

Moved more logic out of the management controller. This also fixes some sensiolabs insights warnings about too long controller actions

Management controller refactoring

---

src/Intracto/Behat/Features/Context/Bootstrap/CommonPartyManagementContext.php
src/Intracto/Behat/Features/started_party_management.feature
src/Intracto/Behat/Features/unstarted_party_management.feature
src/Intracto/SecretSantaBundle/Controller/Participant/ParticipantController.php
src/Intracto/SecretSantaBundle/Entity/ParticipantService.php
src/Intracto/SecretSantaBundle/Resources/config/services.xml
src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.js.twig

- Moved logic to the participant service
- Added missing behat tests for participant edit cases (invalid email, change email)

Moved logic out of the participant edit action

---

composer.lock

this fixes some deprecation warnings

Update dependencies to latest versions

---

composer.lock

See https://symfony.com/blog/cve-2017-11365-empty-passwords-validation-issue
for more info on the security issue. We have no impact of this security issue, nonetheless it's always good to be at the latest patch release!

Update symfony to latest security release

---

.travis.yml
.travis/script.sh
composer.json
composer.lock
docs/behat.md

Same PR as #318 but the travis caches are cleared now

Use ubuntu trusty and upgrade selenium

---

package.json
yarn.lock

See issue https://github.com/symfony/webpack-encore/issues/121#issuecomment-319023942

Update webpack-encore to fix issues with dev --watch task

---

composer.lock
web/config.php

```
Package operations: 0 installs, 17 updates, 0 removals
- Updating symfony/symfony (v3.3.5 => v3.3.6)
- Updating doctrine/inflector (v1.1.0 => v1.2.0)
- Updating doctrine/collections (v1.4.0 => v1.5.0)
- Updating doctrine/cache (v1.6.1 => v1.7.0)
- Updating doctrine/annotations (v1.4.0 => v1.5.0)
- Updating doctrine/common (v2.7.2 => v2.8.0)
- Updating doctrine/dbal (v2.5.12 => v2.6.1)
- Updating doctrine/orm (v2.5.6 => v2.5.8)
- Updating doctrine/doctrine-bundle (1.6.8 => 1.7.0)
- Updating sebastian/object-enumerator (3.0.2 => 3.0.3)
- Updating phpunit/phpunit-mock-objects (4.0.2 => 4.0.4)
- Updating phpunit/php-token-stream (1.4.11 => 2.0.0)
- Updating phpunit/php-code-coverage (5.2.1 => 5.2.2)
- Updating phpunit/phpunit (6.2.3 => 6.2.4)
- Updating sensiolabs/security-checker (v4.0.4 …
```

Updated dependencies to their latest versions

---

.travis/script.sh
src/Intracto/Behat/Features/Context/Bootstrap/PartyContext.php
src/Intracto/SecretSantaBundle/Resources/views/Party/create.html.twig

- Make the create party with csv import test more reliable
- Use the project phpunit executable instead of the travis container executable

Test suite fixes

---

app/AppKernel.php
composer.json
composer.lock
src/Intracto/Behat/DataFixtures/LoadPartyData.php

A simple to improve DX when developing locally with an empty db (to get some pre-filled data)

Added doctrine fixtures bundle to easily load some data in a local db

---

behat.yml.dist
src/Intracto/Behat/Features/Context/Bootstrap/ReportContext.php
src/Intracto/Behat/Features/report.feature

Previous refactorings introduced some issues on the report page. This basic test should avoid any future issues on the report page in new PR's

Added basic report page behat test

---

src/Intracto/SecretSantaBundle/Resources/views/Participant/show/valid.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Party/create.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.html.twig

Css fixes for small screens (table size)

---

.travis/before_install.sh
app/config/config_test_travis.yml
composer.json
composer.lock

Travis ci was broken due to missing parts for geoip

Travis geoip db fixes

---

src/Intracto/Behat/Features/Context/Bootstrap/PartyContext.php

Hopefully this fixes the unreliable test

Try to wait for jquery to finish when testing csv import

---

app/Resources/translations/messages.pt.yml

- Added translations to portuguese.

Improvements:

---

app/Resources/translations/messages.en.yml

Hey guys! Thanks for this great app. Thought I'd open a PR for some small grammar issues since you said contributions were welcome. -Lucas

Fix small grammar and wording issues in messages

---

app/Resources/translations/messages.en.yml

Fix Typo's

---

behat.yml.dist
composer.json
composer.lock

Some composer.json cleanup:
- Set the sort-packages config
- Correct name and description
- Remove useless branch-alias
- Removed "friends-of-behat/performance-extension" as it is useless on php7

Composer.json cleanup

---

deploy.sh
docker/Dockerfile-php
docker/README-docker.md
shell_provisioner/config/apache/dev.secretsantaorganizer.com.conf
shell_provisioner/config/apache/phpmyadmin.dev.secretsantaorganizer.com.conf
shell_provisioner/module/mailhog.sh
shell_provisioner/module/php.sh

- Shell provisioning is upgraded to PHP 7.2
- Build xdebug from source because there is no release yet
- Replace supervisor by systemd script
- I changed but did not test the Docker setup

Upgrade to PHP 7.2

---

composer.json
composer.lock

With the release of phpunit 7, phpunit 5 is not supported anymore

Use latest phpunit version

---

composer.lock
var/SymfonyRequirements.php

running composer update and patching CVE's in the process:
CVE-2018-11407: Unauthorized access on a misconfigured LDAP server when using an empty password — CVE-2018-11407
CVE-2018-11386: Denial of service when using PDOSessionHandler — CVE-2018-11386
CVE-2018-11406: CSRF Token Fixation — CVE-2018-11406
CVE-2018-11408: Open redirect vulnerability on security handlers — CVE-2018-11408
CVE-2018-11385: Session Fixation Issue for Guard Authentication — CVE-2018-11385

composer update

---

app/Resources/translations/messages.de.yml
app/Resources/translations/messages.en.yml
app/Resources/translations/messages.es.yml
app/Resources/translations/messages.fr.yml
app/Resources/translations/messages.nl.yml
app/Resources/translations/messages.no.yml
app/Resources/translations/messages.pl.yml
app/Resources/translations/messages.pt.yml
app/Resources/translations/messages.ru.yml
app/Resources/translations/messages.zh-Hans.yml
app/Resources/translations/messages.zh-Hant.yml
src/Intracto/SecretSantaBundle/Resources/views/Emails/anonymousMessage.html.twig

RFC this seems like an okay solution. See example in #390
This is only implemented in the anonymous message (html) but should be implemented in the txt and in other emails as well. So, WIP

#390: Provide party details in emails

---

src/Intracto/SecretSantaBundle/Resources/views/Emails/emptyWishlistReminder.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/emptyWishlistReminder.txt.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/partyStatus.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/partyStatus.txt.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/removedSecretSanta.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/removedSecretSanta.txt.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/viewParticipantReminder.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/viewParticipantReminder.txt.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/wishlistChanged.html.twig
src/Intracto/SecretSantaBundle/Resources/views/Emails/wishlistChanged.txt.twig

Show party details in all emails sent to participants

---

src/Intracto/SecretSantaBundle/Controller/WishlistController.php
src/Intracto/SecretSantaBundle/Resources/views/Wishlist/showAll.html.twig

Remove "Manage Party" on wishlist page when not referred from manage URL

---

src/Intracto/SecretSantaBundle/Command/SendWishlistUpdatedCommand.php
src/Intracto/SecretSantaBundle/Mailer/MailerService.php
src/Intracto/SecretSantaBundle/Resources/views/Emails/wishlistChanged.html.twig

in the santa update mail the unsubscribe link is wrong. We are unsubscribing the person who sent the update. Not the receiver of the mail

Fix unsubscribe link in wishlist update mail

---

.travis.yml
.travis/before_install.sh
.travis/install.sh
README.md
shell_provisioner/config/apache/dev.secretsantaorganizer.com.conf
shell_provisioner/config/apache/phpmyadmin.dev.secretsantaorganizer.com.conf
shell_provisioner/module/php.sh

Tests pass but we'll wait for 7.3.2 because of stability issues. Atm we encounter segfaults in FPM

PHP 7.3 upgrade

---

app/Resources/translations/messages.en.yml
app/Resources/translations/messages.fr.yml
app/Resources/translations/messages.nl.yml
src/Intracto/SecretSantaBundle/Resources/views/Participant/show/valid.html.twig

Hello ! I try to find big french untranslate sentence and translate in french with different word than the literal translation 
e.g: party => fête this not sound good in french (maybe just for me) so I use Secret Santa for party some time. If french people read this I would like a review and comment ;) 
I hope you like this contribution.

Translate french translation and add a new one in en/fr/nl

---

src/Intracto/SecretSantaBundle/Resources/views/Participant/show/valid.html.twig

ok double adsense blocks are removed and updated with new responsive adsense codes.

SANTA-138: added new responsive adsense codes + update adsense wrappers.

---

app/Resources/translations/messages.en.yml
app/Resources/translations/messages.nl.yml
src/Intracto/SecretSantaBundle/Resources/views/Party/manage/valid.html.twig

Add warning when party already started

---

app/Resources/translations/messages.en.yml
src/Intracto/SecretSantaBundle/Resources/views/Party/create.html.twig
web/sitemap.xml

- Adding the first 2 FAQ questions as structured data on the homepage for better SEO visibility.
- Added missing pages to sitemap.

[SANTA-148][SANTA-149] Added 2 FAQ's to homepage & added missing pages to sitemap

---

README.md
Vagrantfile
shell_provisioner/module/mysql.sh
shell_provisioner/module/php.sh
shell_provisioner/module/phpmyadmin.sh
shell_provisioner/module/yarn.sh

Working debian 11 vagrant config

Santa 178 deb11

---

src/Controller/Api/ApiHelper.php
src/Controller/Api/Party/PartyController.php
src/Entity/Party.php
src/ORM/Mapping/Party.orm.xml
src/Service/PartyService.php

Santa 166 api

---

config/services.yaml
src/Controller/Party/PartyController.php
src/Form/Handler/PartyFormHandler.php
templates/Party/created.html.twig

the party create tests which creates 2 parties is broken because of the rate limiting on party creation
rate limit is disabled for test env

ignore rate limit for test env
